kafka:
  bootstrap_servers:
    - redpanda:9092
  topic_tickets: ticket.events
  group_id: ticket-events-consumer

clickhouse:
  host: clickhouse
  port: 9000
  database: default
  user: default
  password: clickhouse_password

ai:
  address: "ai-service:50051"