FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o consumer ./cmd/consumer

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/consumer .

COPY configs ./configs

EXPOSE 2112

CMD ["./consumer"]