global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "ticket-service"
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "auth-service"
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: "ticket-consumer"
    static_configs:
      - targets: ["host.docker.internal:2112"]