global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "ticket-service"
    static_configs:
      - targets: ["ticket-service:8080"]

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:8081"]
      
  - job_name: "ticket-consumer"
    static_configs:
      - targets: ["consumer:2112"]