// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: ai-service/proto/ai.proto

package ai

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeTicketRequest) Reset() {
	*x = AnalyzeTicketRequest{}
	mi := &file_ai_service_proto_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeTicketRequest) ProtoMessage() {}

func (x *AnalyzeTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeTicketRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeTicketRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_ai_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeTicketRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *AnalyzeTicketRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnalyzeTicketRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AnalyzeTicketRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AnalyzeTicketResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Summary        string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Category       string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Priority       string                 `protobuf:"bytes,3,opt,name=priority,proto3" json:"priority,omitempty"`
	SuggestedReply string                 `protobuf:"bytes,4,opt,name=suggested_reply,json=suggestedReply,proto3" json:"suggested_reply,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeTicketResponse) Reset() {
	*x = AnalyzeTicketResponse{}
	mi := &file_ai_service_proto_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeTicketResponse) ProtoMessage() {}

func (x *AnalyzeTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeTicketResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeTicketResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_ai_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeTicketResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AnalyzeTicketResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AnalyzeTicketResponse) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *AnalyzeTicketResponse) GetSuggestedReply() string {
	if x != nil {
		return x.SuggestedReply
	}
	return ""
}

var File_ai_service_proto_ai_proto protoreflect.FileDescriptor

const file_ai_service_proto_ai_proto_rawDesc = "" +
	"\n" +
	"\x19ai-service/proto/ai.proto\x12\x02ai\"\x84\x01\n" +
	"\x14AnalyzeTicketRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"\x92\x01\n" +
	"\x15AnalyzeTicketResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\tR\bpriority\x12'\n" +
	"\x0fsuggested_reply\x18\x04 \x01(\tR\x0esuggestedReply2Q\n" +
	"\tAIService\x12D\n" +
	"\rAnalyzeTicket\x12\x18.ai.AnalyzeTicketRequest\x1a\x19.ai.AnalyzeTicketResponseB\x15Z\x13ai-service/proto;aib\x06proto3"

var (
	file_ai_service_proto_ai_proto_rawDescOnce sync.Once
	file_ai_service_proto_ai_proto_rawDescData []byte
)

func file_ai_service_proto_ai_proto_rawDescGZIP() []byte {
	file_ai_service_proto_ai_proto_rawDescOnce.Do(func() {
		file_ai_service_proto_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_service_proto_ai_proto_rawDesc), len(file_ai_service_proto_ai_proto_rawDesc)))
	})
	return file_ai_service_proto_ai_proto_rawDescData
}

var file_ai_service_proto_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ai_service_proto_ai_proto_goTypes = []any{
	(*AnalyzeTicketRequest)(nil),  // 0: ai.AnalyzeTicketRequest
	(*AnalyzeTicketResponse)(nil), // 1: ai.AnalyzeTicketResponse
}
var file_ai_service_proto_ai_proto_depIdxs = []int32{
	0, // 0: ai.AIService.AnalyzeTicket:input_type -> ai.AnalyzeTicketRequest
	1, // 1: ai.AIService.AnalyzeTicket:output_type -> ai.AnalyzeTicketResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_service_proto_ai_proto_init() }
func file_ai_service_proto_ai_proto_init() {
	if File_ai_service_proto_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_service_proto_ai_proto_rawDesc), len(file_ai_service_proto_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_service_proto_ai_proto_goTypes,
		DependencyIndexes: file_ai_service_proto_ai_proto_depIdxs,
		MessageInfos:      file_ai_service_proto_ai_proto_msgTypes,
	}.Build()
	File_ai_service_proto_ai_proto = out.File
	file_ai_service_proto_ai_proto_goTypes = nil
	file_ai_service_proto_ai_proto_depIdxs = nil
}
